# Configuration for Netlify deployment
# Rename this file to config.yml when deploying to Netlify and replace the existing config.yml

backend:
  name: git-gateway
  branch: main # or your default branch

# Enable authentication
auth:
  providers:
    - name: git-gateway
      roles: [admin, editor]

# Media configuration for Netlify
media_folder: "client/public/assets/uploads"
public_folder: "/assets/uploads"

# Site configuration
site_url: https://your-site-name.netlify.app  # Replace with your Netlify URL
display_url: https://your-site-name.netlify.app

# Collections (same as development version)
publish_mode: editorial_workflow
slug_encoding: "ascii"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Landing Page"
        name: "landing"
        file: "client/public/assets/content/landing.json"
        fields:
          - label: "Header Title"
            name: "header_title"
            widget: "string"
            required: false
            hint: "Text for the header logo/brand."
          - label: "Back to Coming Soon Link Text"
            name: "back_to_coming_soon_text"
            widget: "string"
            required: false
            hint: "Text for the link back to the coming soon page."
          # ... rest of fields (copy from main config.yml)

      - label: "Coming Soon Page"
        name: "coming_soon"
        file: "client/public/assets/content/coming-soon.json"
        fields:
          # ... fields (copy from main config.yml)

      - label: "Vessel Teaser Page"
        name: "vessel_teaser"
        file: "client/public/assets/content/vessel.json"
        fields:
          # ... fields (copy from main config.yml)